
[package]
name = "lazuli"
version = "0.1.1"
edition = "2021"

[workspace]
members = ["lazuli_core", "lazuli_derive"]

[workspace.package]
version = "0.1.0"


[dependencies]
lazuli_core = { path = "lazuli_core" }
lazuli_derive = { path = "lazuli_derive" }

